### ISSUE TITLE
Test Cases/NISA/main FAILED. Reason: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/VisualInspectionOfExcelAndPDF#11]
I executed Test Cases/NISA/main, it failed.

```
2023-04-27 07:34:47.648 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/NISA/main FAILED.
Reason:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.kazurayam.materialstore.core.MaterialList.get(MaterialList.java:63)
	at com.kazurayam.materialstore.diagram.dot.DotGenerator.generateDotOfMPGBeforeZip(DotGenerator.java:203)
	at com.kazurayam.materialstore.diagram.dot.MPGVisualizer.visualize(MPGVisualizer.java:32)
	at com.kazurayam.inspectus.core.internal.ChronosDiff.step3_reduceChronos(ChronosDiff.java:93)
	at com.kazurayam.inspectus.core.internal.ChronosDiff.process(ChronosDiff.java:34)
	at com.kazurayam.inspectus.core.Inspectus.execute(Inspectus.java:11)
	at com.kazurayam.inspectus.core.Inspectus$execute.call(Unknown Source)
	at main.run(main:41)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:144)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:135)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1682548451349.run(TempTestCase1682548451349.groovy:25)

2023-04-27 07:34:47.663 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/NISA/main FAILED.
Reason:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.kazurayam.materialstore.core.MaterialList.get(MaterialList.java:63)
	at com.kazurayam.materialstore.diagram.dot.DotGenerator.generateDotOfMPGBeforeZip(DotGenerator.java:203)
	at com.kazurayam.materialstore.diagram.dot.MPGVisualizer.visualize(MPGVisualizer.java:32)
	at com.kazurayam.inspectus.core.internal.ChronosDiff.step3_reduceChronos(ChronosDiff.java:93)
	at com.kazurayam.inspectus.core.internal.ChronosDiff.process(ChronosDiff.java:34)
	at com.kazurayam.inspectus.core.Inspectus.execute(Inspectus.java:11)
	at com.kazurayam.inspectus.core.Inspectus$execute.call(Unknown Source)
	at main.run(main:41)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:144)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:135)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1682548451349.run(TempTestCase1682548451349.groovy:25)

2023-04-27 07:34:47.690 INFO  c.k.katalon.core.main.TestCaseExecutor   - END Test Cases/NISA/main

```

I had no `store` directory, I had no `store-backup` directory.

**Comment by kazurayam** [comment]
DotGenerator:
```
public static String generateDotOfMPGBeforeZip(MaterialProductGroup mProductGroup,
                                                   Map<String, String> options,
                                                   boolean standalone) {
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        String sequenceNumber = options.getOrDefault("sequenceNumber", "0");
        ...
        MaterialList leftML = mProductGroup.getMaterialListLeft();
        Material leftTop = leftML.get(0);
        ...
```

When the leftML.size() == 0, then a call to `leftML.get(0)` will throw an IndexOutOfBoundsException.

**Comment by kazurayam** [comment]
https://github.com/kazurayam/materialstore/issues/413 fixed this

**Comment by kazurayam** [comment]
done at [v0.14.2-SNAPSHOT](https://github.com/kazurayam/VisualInspectionOfExcelAndPDF/releases/tag/0.14.2-SNAPSHOT)
