### ISSUE TITLE
Test Suite "NISA" failed because the Excel sheets strucuture changed March 2022 and April 2022

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/VisualInspectionOfExcelAndPDF#3]
7th April 2022, when I executed NISA, it failed.

<img width="1552" alt="スクリーンショット 2022-04-06 13 53 01" src="https://user-images.githubusercontent.com/4467417/161898491-b50d9e3d-fd4e-438e-ba80-8fa6bf8839b8.png">

StoreImpl#reflect(MaterialList) does not work as expected.

**Comment by kazurayam** [comment]
```
2022-04-06 13:42:05.865 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] all.size()=5
2022-04-06 13:42:05.866 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] aft[0]=20220406_134203
2022-04-06 13:42:05.866 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] aft[1]=20220406_134151
2022-04-06 13:42:05.866 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] aft[2]=20220307_100622
2022-04-06 13:42:05.866 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] aft[3]=20220307_100620
2022-04-06 13:42:05.866 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] aft[4]=20220307_100608
2022-04-06 13:42:05.868 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] filtered.size()=4
2022-04-06 13:42:05.869 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] jft[0]=20220406_134151
2022-04-06 13:42:05.869 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] jft[1]=20220307_100622
2022-04-06 13:42:05.869 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] jft[2]=20220307_100620
2022-04-06 13:42:05.869 DEBUG c.k.materialstore.filesystem.StoreImpl   - [queryAllJobTimestampsPriorTo] jft[3]=20220307_100608
2022-04-06 13:42:05.869 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] allJobTimestamps.size()=4
2022-04-06 13:42:05.869 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] previous=20220406_134151
2022-04-06 13:42:05.871 DEBUG c.k.materialstore.filesystem.StoreImpl   - [similar] baseList.size()=15 != count=0
2022-04-06 13:42:05.871 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] previous=20220406_134151 is not similar to base=20220406_134203
2022-04-06 13:42:05.871 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] previous=20220307_100622
2022-04-06 13:42:05.887 DEBUG c.k.materialstore.filesystem.StoreImpl   - [similar] baseList.size()=15 != count=0
2022-04-06 13:42:05.887 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] previous=20220307_100622 is not similar to base=20220406_134203
2022-04-06 13:42:05.887 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] previous=20220307_100620
2022-04-06 13:42:05.901 DEBUG c.k.materialstore.filesystem.StoreImpl   - [similar] baseList.size()=15 != count=0
2022-04-06 13:42:05.901 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] previous=20220307_100620 is not similar to base=20220406_134203
2022-04-06 13:42:05.902 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] previous=20220307_100608
2022-04-06 13:42:05.904 DEBUG c.k.materialstore.filesystem.StoreImpl   - [similar] baseList.size()=15 != count=0
2022-04-06 13:42:05.904 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] previous=20220307_100608 is not similar to base=20220406_134203
2022-04-06 13:42:05.904 DEBUG c.k.materialstore.filesystem.StoreImpl   - [reflect] returning MaterialList.NULL_OBJECT
2022-04-06 13:42:05.905 INFO  c.k.m.reduce.MProductGroupBuilder        - [chronos] jobName=NISA, store=/Users/kazuakiurayama/katalon-workspace/VisualInspectionOfExcelAndPDF/store
2022-04-06 13:42:05.905 INFO  c.k.m.reduce.MProductGroupBuilder        - [chronos] previousMaterialList.getJobTimestamp()=_
2022-04-06 13:42:05.905 INFO  c.k.m.reduce.MProductGroupBuilder        - [chronos] previousMaterialList.size()=0
2022-04-06 13:42:05.905 INFO  c.k.m.reduce.MProductGroupBuilder        - [chronos] currentMaterialList.getJobTimestamp()=20220406_134203
2022-04-06 13:42:05.905 INFO  c.k.m.reduce.MProductGroupBuilder        - [chronos] currentMaterialList.size()=15
2022-04-06 13:42:05.913 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/Patrol/NISA/reduce FAILED.
Reason:
com.kazurayam.materialstore.MaterialstoreException: previousMaterialize.size() == 0
	at com.kazurayam.materialstore.reduce.MProductGroupBuilder.chronos(MProductGroupBuilder.java:39)
	at com.kazurayam.materialstore.reduce.MProductGroupBuilder$chronos.call(Unknown Source)
```

The script failed to find the previousMaterialList

**Comment by kazurayam** [comment]
JobTimestamp=20220307 had 14 Materials, while JobTimestamp=20220406 has 15 Materials.

<img width="1552" alt="スクリーンショット 2022-04-06 13 56 36" src="https://user-images.githubusercontent.com/4467417/161898798-6c52cca7-1229-4676-a642-97342fee4738.png">

This means, the Excel file has been changed. 1 Sheet has been added.

I wonder if the StoreImpl#similar method works appropriately or not in this case
